language: ruby
sudo: false
dist: xenial
rvm:
  - 2.6.5

before_install:
  - bundle install

services:
  - postgresql

env:
  - DATABASE_USERNAME=postgres DATABASE_PASSWORD= DATABASE_HOST=127.0.0.1 DATABASE_PORT=5432

script:
  - rails db:setup

branches:
  only:
    - master

cache:
  directories:
  - .autoconf

deploy:
  provider: heroku
  api_key:
    secure: a8PT07votSEmv4pyLS4C9My7UTFtmnkJG6HvVWTQ6XYg0pXGEWmSe3/IeJ+5My3Uri5JHDhnyXirsVTlxvLatWfQfKAjtD7a5Y1FFQ3DVOlMtj4NjPAPz0aJ4aq/94BPmsKW32QJtZRT4qX3fet2CVKFpmDzjZQ7xkP0UiHtWClv18n4SpBox6wsqHj6+wswIRhP2NJWjjnSvdPCJhrFP67k/jKWoYBDNrvzAxBkyNgzQkRoDf9buyqWJMtqd2PoBGWXydZKhzbAdadfGAyY9291hT86AMWvKnFoaIb5CD4MFbc8LTMnp98IINRwayUW2nvePDAqaULqJJqUTjMYEKCCD+5ewlS8ttsohoWPJPGecyUS+WWLnT/Mapkt/3bkEdh5iBMkovhppMHtzVK+SIFj+eG2WAYkfeltCVGs9AP6O5I1q4CchJ7XyCR+txwBFamFbgFmphd22nR+qcLpsuC7582O7Vi/pozPp7w5Bn1YKabIWv70I+p023YpJ+Tf5VRK0ITLhuLAUC17svj1qcFhfeNRSiRUkW9iDESUKrdRxsXori9f/8acyyfqgLWtW0xX8GJbFxgQ9b8YDyCfVrumjv7qPcsIiC0Q6dt+OtkK7wptCUurJ6V5C4A73ufEt6BAUooo2RNr6A/cmVNSuMo7xENcCSPILNVLbQJPoTQ=
  app: activeadmin-demo
  on:
    repo: mkdika/active-admin-demo

notifications:
  email:
    recipients:
      - mkdika@gmail.com
    on_success: always
    on_failure: always